services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app

  php:
    build:
      context: ./docker/php
    volumes:
      - ./www:/var/www/html
    networks:
      - app

networks:
  app:
    driver: bridge